global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'beyla'
    static_configs:
      # Sửa IP này thành IP máy chủ của bạn (IP bạn vừa gõ trên trình duyệt)
      - targets: ['103.48.195.8:8999']
